name: publish website
run-name: $publish website
on: [push]
  
jobs:
  update_site:
    runs-on: ubuntu-latest
    steps:
      - name: "Update qlbbl.com"
        uses: D3rHase/ssh-command-action@latest
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          private_key: ${{ secrets.SSH_KEY }}
          command: ./update_qlbbl.sh
