name: publish website
run-name: $publish website
on: [push]

env:
  SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
  
jobs:
  update_site:
    runs-on: ubuntu-latest
    steps:
      - name: "Update qlbbl.com"
        uses: D3rHase/ssh-command-action@latest
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_PRIVATE_KEY }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          command: ./updateqlbbl.sh
